# Generated by Django 3.1.7 on 2021-03-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Category')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('category_photo', models.ImageField(blank=True, null=True, upload_to='category_photo/', verbose_name='Изображение')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField()),
                ('desc', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Наименование товара')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('status', models.IntegerField(choices=[(1, 'Еще не начат'), (2, 'В ожидании оплаты'), (3, 'Успешно завершено')], verbose_name='Status of lot')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lot_photo/', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='LotDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала лота')),
                ('date_of_applying', models.DateField(verbose_name='Дата срока подачи заявки')),
                ('first_date_osmotr', models.DateField(verbose_name='Первый день осмотра')),
                ('second_date_osmotr', models.DateField(blank=True, null=True, verbose_name='Второй день осмотра')),
                ('third_date_osmotr', models.DateField(blank=True, null=True, verbose_name='Третий день осмотра')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.lots', verbose_name='Лот')),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_amount', models.FloatField(verbose_name='Стартовая цена')),
                ('assessed_value', models.FloatField(blank=True, null=True, verbose_name='Оценочная стоимость')),
                ('percent_deposit', models.FloatField(verbose_name='Закладные проценты')),
                ('deposit_amount', models.FloatField(blank=True, null=True, verbose_name='Сумма закалата')),
                ('percent_step', models.FloatField(verbose_name='Процент шага')),
                ('first_step', models.FloatField(blank=True, null=True, verbose_name='Первый шаг')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.lots', verbose_name='Лот')),
            ],
            options={
                'verbose_name': 'Сумма за лот',
                'verbose_name_plural': 'Суммы за лоты',
            },
        ),
    ]
