# Generated by Django 3.1.7 on 2021-03-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_category_banner_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(db_index=True, max_length=128, verbose_name='Поле-1')),
                ('field2', models.CharField(db_index=True, max_length=128, verbose_name='Поле-2')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.category', verbose_name='Категория')),
            ],
        ),
    ]
